[main]
environment = "packet"
debug = false

#### Environment default ####

[environment.default]
provider = "gns3-lab"
# provider = "container-lab"

[environment.default.notifications]
service = "slack"
channel = "general"

[environment.default.providers.container-lab]
kind = "vrnetlab"
server_url = "tcp://docker-host.ec2.aws:2375"
verify_cert = true

[environment.default.providers.gns3-lab]
kind = "gns3"
server_url = "http://gns3-server:80"
verify_cert = false

#### Environment aws ####

[environment.aws]
provider = "gns3-us-server"

[environment.aws.meta]
region = "us-east"


[environment.aws.nornir_runner]
plugin = "threaded"
options = { num_workers = 20 }

[environment.aws.providers.gns3-us-server]
kind = "gns3"
server_url = "http://gns3-us-east-server.aws:80"
verify_cert = true
# Also can be set as env variables
user = "netops"
password = "netops123"

#### Environment packet ####

[environment.packet]
provider = "gns3-main"

[environment.packet.providers.gns3-main]
kind = "gns3"
server_url = "http://147.75.199.202:3080"
verify_cert = false
