[labby]
environment = "local"
provider = "gns3"

[labby.notifications]
service = "slack"
channel = "general"

[labby.provisioner.nornir.runner]
plugin = "threaded"
options = { num_workers = 20}

[labby.provisioner.nornir.inventory]
plugin = "SimpleInventory"
options = {host_file = "inventory/hosts.yml", group_file = "inventory/groups.yml"}

[environment.local.gns3]
server_url = "http://gns3-server:80"
verify_cert = false

[environment.aws.gns3]
server_url = "http://ec2.aws.gns3-server:80"
verify_cert = false

[environment.aws.vrnetlab]
docker_host = "tcp://ec2.aws.docker-host:2375"
verify_cert = true

[environment.packet.eve_ng]
server_url = "http://packet.even-ng-server.local"
user = "user1"
password = "password1"
